### ISSUE TITLE
rename/reorganize does not work for controladdins

### ISSUE THREAD

**Issue by ChrisBlankDe** [waldo1001/crs-al-language-extension#103]
controladdin does get automatically a prefix or suffix if configured.
controladdin file is not renamed
controladdin file will only moved in the src/al/... directory. No Subfolder for this object type -> would like to have a automatically created structure like this:
```
AL
- ControlAddIn
-- MyAddin
--- MyAddin.al
--- Scripts
--- StyleSheets
--- Images
```

**Comment by ChrisBlankDe** [comment]
Maybe Problem start at loading object properties where controladdin is not listed in object type Pattern.
https://github.com/CloudReadySoftware/crs-al-language-extension/blob/master/src/NAVObject.ts#L104

But that's only a maybe. TypeScript is not one of my talents.

**Comment by waldo1001** [comment]
The reason why there is no rename/reorg is because Microsoft hasn't got any guideline for it:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode

What I could do for the structure, is generate the code somehow, like creating a command (command palette) "Create Control Add-In", that basically creates the folder and the control add in as you mention. Would that make sense?

**Comment by ChrisBlankDe** [comment]
That would be really helpfull.
but please make sure not to move the controladdin al file back to the src/al Folder.

**Comment by waldo1001** [comment]
To be honest, I'd like to remove all "reorganize" commands as I don't believe they should be used (I never do)...

**Comment by ChrisBlankDe** [comment]
Why? I love them. When creating a new Object I always generate a shitty filename in root Directory and only care about the object name. CRS: Reorganize do all dull work for me. It become essential like Reformat at saving.

**Comment by waldo1001** [comment]
Ok, I'll leave it, but I don't like to structure my fields by object type :-).  I have a subfolder for each "functional item", and all object types for that functionality are int here...

**Comment by ChrisBlankDe** [comment]
Meanwhile, Microsoft has added a prefix for ControlAddins: ConAddin,
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#type-map

Could you add this to your List?

**Comment by waldo1001** [comment]
Yes, it's pretty high on my list - but so much more to do :(.  Thanks for the link!

**Comment by waldo1001** [comment]
Hi @ChrisBlankDe ,

Here is a new version of the VSIX:
https://www.dropbox.com/s/6xl8ue7u4nx0vf3/crs-al-language-extension-1.1.13.vsix?dl=0

Which should have implemented the controladdin.  Looks good as it is.

I wasn't abel to get all your files moved to the new folder, only the one that is being re-organized. 

Just give it a go when you have the chance...

**Comment by ChrisBlankDe** [comment]
Rename works perfectly.
Reorganize doesn't work for me at all. None files are moved. Src folder will be created.
Tested with this mini App:
[TestApp.zip](https://github.com/waldo1001/crs-al-language-extension/files/3358771/TestApp.zip)

**Comment by waldo1001** [comment]
@ChrisBlankDe ,

new version online, same link: 
https://www.dropbox.com/s/6xl8ue7u4nx0vf3/crs-al-language-extension-1.1.13.vsix?dl=1

I wasn't able to create folder and subfolder at the same time - and I must have had the folder already when I tested it... too bad it's very hard to do file-related stuff in testability ;-)

**Comment by ChrisBlankDe** [comment]
Nothing happens when Reorganize Current File.
Error when Reorganize all:
`ENOENT: no such file or directory, mkdir 'c:\Users\cblank\Documents\AL\ALProject14\src\controladdin\MyControlAddIn'`

**Comment by waldo1001** [comment]
Damn, I have no idea .. can't replicate that.. .  This is what happens on my side...
![22A6304D-271C-4920-96F1-AE7C1FD7ACC1](https://user-images.githubusercontent.com/12088142/60663625-09cd2880-9e60-11e9-8334-f588ba109fc0.GIF)

**Comment by waldo1001** [comment]
Can you share all your CRS settings?

**Comment by ChrisBlankDe** [comment]
None on Workspace Level
User Settings:
```
{
    "workbench.colorTheme": "Visual Studio Light",
    "workbench.editor.highlightModifiedTabs": true,
    "workbench.colorCustomizations": {
        "activityBarBadge.background": "#d00000"
    },
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.cursorBlinking": "expand",
    "files.trimFinalNewlines": true,
    "git.ignoreMissingGitWarning": true,
    "git.confirmSync": false,
    "team.showWelcomeMessage": false,
    "CRS.DisableCRSSnippets": false,
    "CRS.DisableDefaultAlSnippets": true,
    "CRS.RenameWithGit": true,
    "todo-tree.showCountsInTree": true,
    "vsicons.dontShowNewVersionMessage": true
}
```

**Comment by ChrisBlankDe** [comment]
weird. 
i quickly build up an azure machine to test it again in a clean environment.

**Comment by ChrisBlankDe** [comment]
> i quickly build up an azure machine to test it again in a clean environment.
Problem must be on my machine. Works fine in Azure. Even with my settings and extensions..

i think you can release it in the next version like this.

**Comment by waldo1001** [comment]
Aight!  Keep me posted what the problem was - and if I should change something ;-)
