### ISSUE TITLE
Setting to strip non-alphanumeric characters from pattern-generated extension object names

### ISSUE THREAD

**Issue by rvanbekkum** [waldo1001/crs-al-language-extension#115]
Hello @waldo1001,

I think this issue is best explained through an example.
Let's say I have the following settings to automatically set the generated extension object name when renaming:
![example_settings](https://user-images.githubusercontent.com/7383241/58368220-42d1bf00-7eea-11e9-86de-dd3d1763542e.png)
Then, when I would create an extension on page 18 "G/L Account List", I would get the following extension object name from this pattern:
![current_result](https://user-images.githubusercontent.com/7383241/58368237-83c9d380-7eea-11e9-966a-da820e5503dd.png)

However, the name I would actually like to have based on this extension object name pattern is the following:
```pascal
pageextension 50100 ABCGLAccountList extends "G/L Account List"
```
so stripping all non-alphanumeric characters from the suggested extension object name and removing the surrounding quotes.

Is this something you could add as a new setting (e.g., `CRS.StripNonAlphanumericCharactersFromObjectNames`, see also the [AL Code Outline extension](https://github.com/anzwdev/al-code-outline) that has such a extension) in your extension? A setting that strips all non-alphanumeric characters in extension object names and will then also drop the unnecessary, surrounding quotes.

**Comment by waldo1001** [comment]
Makes sense - I will have a look.  Thanks!

**Comment by waldo1001** [comment]
@rvanbekkum ,

I just realized - did you try the following setting:
![image](https://user-images.githubusercontent.com/12088142/58511598-738c4f80-819b-11e9-99cd-fac803642d26.png)

You can find all possible patterns by using the tooltip:
![image](https://user-images.githubusercontent.com/12088142/58511642-856df280-819b-11e9-88ae-a5c889c427d7.png)

Does this solve your problem?

**Comment by rvanbekkum** [comment]
Hi @waldo1001,
That seems to give the output that I wanted, thank you for pointing it out. 😄 
I have one 'issue' with it though (i.e., always adding quotes), but I decided to leave that as a comment in issue #114, because I think it's more related to that one.
