### ISSUE TITLE
snippet too invasive

### ISSUE THREAD

**Issue by stefanoPrimo** [waldo1001/crs-al-language-extension#121]
Hi,
I've found this bug that appears any time I write down the "then" keyword with space after it and every time I press enter in order to create a new line after the if statement it will execute the snippet as you can see in the screenshot. 
Thanks
Stefano Primo
![image](https://user-images.githubusercontent.com/36199751/59033866-0eef8580-886a-11e9-89a9-5a6b8bd6f3cd.png)

**Comment by waldo1001** [comment]
That's default snippet functionality, I'm afraid.  Not a bug.

Can I ask - it's a "then" from which statement"?  Can you share some more code?

You can try to play with these settings:
![image](https://user-images.githubusercontent.com/12088142/59036473-a99e9300-886f-11e9-89a8-5cb6a1cdac5f.png)

**Comment by stefanoPrimo** [comment]
![image](https://user-images.githubusercontent.com/36199751/59037832-55e17900-8872-11e9-82b4-c0d2ff4fbea5.png)

usually happens with the IF statement.
adding this setting:
`"editor.suggest.filterGraceful": false,`
it seems to solve a little bit the problem

**Comment by waldo1001** [comment]
hm, the problem is the space - because of the space in the snippetprefix, it actually is still valid for the current suggestion list.

I agree - doesn't make sense - will change! :-)

**Comment by stefanoPrimo** [comment]
thanks a lot,
If you want I could beta test it!
let me know!

**Comment by waldo1001** [comment]
Update is online now!
