### ISSUE TITLE
snippet failing on pages which has field name with any kind of abbreviation

### ISSUE THREAD

**Issue by omurcanates** [waldo1001/crs-al-language-extension#122]
Hi all,
 
I believe last commit for [CRS AL Language Extension](https://github.com/waldo1001/crs-al-language-extension/commit/2e2e0964bd1e5d3837b51a708a6623a71b3f6c28) is failing on field names. It is looking for the name and if its only one word, quotation mark is taken out but it is also doing this for the abbreviated names. 
Example:
![image](https://user-images.githubusercontent.com/51468134/59077813-3b6dd500-8930-11e9-8212-163cfa8052b9.png)
The second we save with CRS enabled, its doing this: 
![image](https://user-images.githubusercontent.com/51468134/59077854-71ab5480-8930-11e9-884b-bffb19853337.png)
Also, doing this for shortcut keys as well. :
![image](https://user-images.githubusercontent.com/51468134/59077991-188ff080-8931-11e9-8da5-febae8192208.png)
Hence, it is not compiling anymore and you are stuck in a situation which you cant go back. Unless you open the al file in notepad and save push.

**Comment by waldo1001** [comment]
thanks for the feedback!
Should be fixed with: https://github.com/waldo1001/crs-al-language-extension/commit/cf2b7f14493b0d5c01aeaa9b9d06e79411d06a4f

pushing an update now!
