### ISSUE TITLE
ControlNames are no longer surrounded double quotes

### ISSUE THREAD

**Issue by fvet** [waldo1001/crs-al-language-extension#124]
@waldo1001 

It seems like control names / field names (containing one word / no spaces only) were enclosed by " in previous versions. When **saving** an existing AL file with the latest CRS extension, the " are removed?

![image](https://user-images.githubusercontent.com/25268332/59499371-930fc180-8e97-11e9-926e-2514c7671e11.png)

Seems like this only occurs when CRS extension is installed, e.g. with settings below, upon **saving** the file. Is this a recent change by the CRS extension and how to cope with it?

![Quotes](https://user-images.githubusercontent.com/25268332/59499480-c5212380-8e97-11e9-9b86-6e9ccede8078.gif)

https://github.com/microsoft/AL/issues/5060

**Comment by waldo1001** [comment]
It is a recent change, because it caused bugs ... like:
https://github.com/waldo1001/crs-al-language-extension/issues/114
https://github.com/waldo1001/crs-al-language-extension/pull/123

What don't you like about it?

**Comment by waldo1001** [comment]
I understand it gives you changes in formatting, but in all honesty, it's for the best.  May be the best way to cope with it is: 
- rename all
- commit with comment "Remove unnecessary double quotes for fieldnames"

then you only have to cope with it once...

**Comment by fvet** [comment]
Makes sense reading through the previous issues. Will indeed to a full rename once to get all code updated. Thx.

**Comment by waldo1001** [comment]
may be it's worth a blogpost ;-)
