### ISSUE TITLE
Multi Root workspaces: reopen after rename acts weird

### ISSUE THREAD

**Issue by waldo1001** [waldo1001/crs-al-language-extension#128]
When unsaved workspace, it seems to reopen an empty file
when saved workspace, it doesn't reopen at all

**Comment by marknitek** [comment]
It seems it is related to renamewithgit because without that setting i don't have any issues.
Also i get this error message:
```
29.8.2019, 12:15:56 - * fallback: renaming without git from 1.al to Cod50996.GLTtestxx.al
29.8.2019, 12:15:56 - * you might want to set the setting "crs.RenameWithGit" to false for this workspace.
29.8.2019, 12:15:56 - ***
29.8.2019, 12:18:22 - *** Warning
29.8.2019, 12:18:22 - * fatal: not under version control, source=foundation/al/tables/1.al, destination=foundation/al/tables/Tab50996.GLTMyTablexyz.al
```

**Comment by waldo1001** [comment]
Could it be it only happens when the file is not in git yet?  When you would commit it, it does work?

**Comment by marknitek** [comment]
I think so, i have to test that, but i rename on save an therefore this happens for new files all the time at the first save...
So i disabled renamewithgit because i dont realy need it. 
But i would prefer to have it enabled.

**Comment by waldo1001** [comment]
Well, if you don’t have git, you will always have those “errors”, as it tries to rename with git first.  I didn’t find a way to test if it is a git-source-controlled workspace .. sorry.

**Comment by marknitek** [comment]
Of course we use git! But the renamewithgit is only useful wenn you rename many files in one commit... If you just have to rename a few (which is the most common scenario 99%) it is not needed sunce git figures it out itself.
When i have time i debug the issue and make a PR.

**Comment by waldo1001** [comment]
that would be awesome :-).
my time is limited at this moment ..

**Comment by marknitek** [comment]
I created a PR #132  let me know what you think about it.

**Comment by waldo1001** [comment]
Thanks so much – I will try to have a look tomorrow evening!

**Comment by waldo1001** [comment]
at this point, I don't find a decent solution, but I have implemented a fix that makes it more stable.. .

**Comment by marknitek** [comment]
From what i see there is no real fix but a warning if you use multiroot? 
Thats a bit sad since we know its a async timing problem which can be solved...

**Comment by waldo1001** [comment]
I know, sorry, I tried, but I'm not good enough, apparently.  I really hoped your solution would have worked.. .

I do wonder, however, when a file is dragged and dropped in the explorer of VSCode - why isn't it "git mv"-ed either.. .  May be it just isn't possible?

Dunno .. but at least, it's somewhat more stable now.. .

**Comment by waldo1001** [comment]
But please - I'd really appreciate you or anyone else to have a go at it (again ;-))...
