### ISSUE TITLE
Surround Keywords with doublequotes

### ISSUE THREAD

**Issue by HerrRiebmann** [waldo1001/crs-al-language-extension#129]
When a fieldname is equal to a keyword, it leads to an error:

> identifier expected; 'grid' is a keyword

Since doublequotes are getting removed, if the name does not contain special chars or spaces, you cannot circumvent this.

The basic keywords should be respected in [encloseInQuotesIfNecessary](https://github.com/waldo1001/crs-al-language-extension/blob/master/src/StringFunctions.ts):
- codeunit
- grid
- table
- page
- profile
- etc.

**Example:**
```
field(114; Grid; Boolean)
{
    Caption = 'Grid';
    DataClassification = CustomerContent;
}

```

**Solution:**
```
field(114; "Grid"; Boolean)
{
    Caption = 'Grid';
    DataClassification = CustomerContent;
}

```

Off course it is not the best naming convention, to call a field "grid" or "profile"... But I have to support legacy code, which converts a table into json.
Thanks a lot :)

**Comment by waldo1001** [comment]
Thanks for creating the issue.

Although I have a principal issue with calling this a "bug" .. I'll still do so ;-).  Indeed, in case of legacy it should be dealt with.

I'll do my best...

**Comment by waldo1001** [comment]
Hi, I'm working on this - but I am confused.  I'm not able to replicate this behaviour.
Can you share all your CRS.-settings with me - just to simulate the behaviour?

In my case, if you just put quotes around them yourself - it would accept the value.. .

**Comment by waldo1001** [comment]
I got a usecase: 
A setting for prefix in combination with a table with these field names...

**Comment by waldo1001** [comment]
Hi @HerrRiebmann ,

I have a test-version ready.  You can download it here:
https://www.dropbox.com/s/3qafb1eucgxdo47/crs-al-language-extension-1.1.12.vsix?dl=1

just install it manually in VSCode by:
![image](https://user-images.githubusercontent.com/12088142/60649577-8b15c280-9e42-11e9-9bce-ba7fac6927dc.png)

**Comment by HerrRiebmann** [comment]
Hi waldo,
thank you very much for working on this!
I could not answer fast enough until you already fixed this issue (_since it is not a bug_ ;) ).

Tested you version and it works fine 👍 

PS:
I´ll celebratory promise to you to rename the table field as fast as I could.

**Comment by waldo1001** [comment]
No prob - another happy user, I hope ;-).

It will be in the next release (today).  You should get an update automatically .. although, I'm not sure since you now manually installed the vsix.
