### ISSUE TITLE
Reorganizing controladdin ignores CRS.RemoveSuffixFromFilename option

### ISSUE THREAD

**Issue by nicolassaleron** [waldo1001/crs-al-language-extension#131]
Hello,

After the last release (1.1.15) and the new feature to reorganize controladdin, I have noticed the suffix is kept on the folder name automatically created.

For instance if I have:
```
controladdin "My Control Add In SFX" { }
```

where SFX is my suffix, the controladdin file is renamed ConAddin.MyControlAddIn.al but it is moved to /src/controladdin/My Control Add In **SFX**/

Is it done on purpose?

The folder name also keeps spaces and not filenames. It seems to create error at runtime when their is spaces in the script/css path.

**Comment by waldo1001** [comment]
Not on purpose ... I will take a look...

Sent from my iPhone

On 6 Jul 2019, at 09:11, nicolassaleron <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

After the last release (1.1.15) and the new feature to reorganize controladdin, I have noticed the suffix is kept on the folder name automatically created.

For instance if I have:

controladdin "My Control Add In SFX" { }


where SFX is my suffix, the controladdin file is renamed ConAddin.MyControlAddIn.al but it is moved to /src/controladdin/My Control Add In SFX/

Is it done on purpose?

The folder name also keeps spaces and not filenames. It seems to create error at runtime when their is spaces in the script/css path.

**Comment by waldo1001** [comment]
I think I solved the issues - using the "short" names now ;-).  Update is online!  Thanks for taking the time to report this with extensive information :-) - big help!
