### ISSUE TITLE
Add option to always capitalize object type in filename

### ISSUE THREAD

**Issue by cvale** [waldo1001/crs-al-language-extension#139]
When using object type as part of file name (MyPage.page.al), object type first character case is the sam as object definition inside AL file, eg. if you start your object definition with capital letter:
Page 5000 MyPage you get MyPage.Page versus 
page 5000 MyPage where you get MyPage.page...

Can you please add a boolean option to always capitalize first letter of the object type?

Thanks

**Comment by cvale** [comment]
I cloned your repository and made this change... I am not sure if I have a permission to create a pull request in the repo?

**Comment by waldo1001** [comment]
you can always create a pullrequest .. I'll review it when I get it.

Thanks in advance!

**Comment by cvale** [comment]
I can do that, but it seems that I do not have write access so I can not create a new branch. Maybe I'm doing something wrong... Can you please advise?

**Comment by waldo1001** [comment]
You need to fork this repo to your own account, then you get your own repo, which you can clone and do changes in .. after that, you can create a pullrequest to this one ... .

**Comment by waldo1001** [comment]
Isn't it the same as this:
https://github.com/waldo1001/crs-al-language-extension/issues/141
