### ISSUE TITLE
File Name patterns for new BC versions

### ISSUE THREAD

**Issue by ernestasjuska** [waldo1001/crs-al-language-extension#141]
Hi,

New code analysers from AL Language extension shows warning if file is not named correctly.
E.g: `table 123 "PREFIX My Demo"` should be in file `PREFIXMyDemo.Table.al`, and `page extension 1234 "PREFIX My Demo Ext" extends "Standard Page"` should be in file `PREFIXMyDemoExt.PageExt.al`.

My initial guess was to use this:
```json
		"CRS.FileNamePattern": "<ObjectNameShort>.<ObjectType>.al",
		"CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectType>.al",
		"CRS.FileNamePatternPageCustomizations": "<ObjectNameShort>.PageCust.al"
```

This does not correctly capitalize object type (e.g. gives "codeunit" intead "Codeunit"), and does not give shorter extension object type (e.g. gives "pageextension" instead "PageExt").

I'm using AL Language extension 5.0.191295 (that's from insider BC version).

IMHO all that is missing is `<ObjectTypeShortPascalCase>` that would give "Table", "Page", "Codeunit", "Report", "Query", "XmlPort", "Enum", "TableExt", "PageExt", "EnumExt", "PageCust".

Analyser does not consider case however it PascalCase looks nicer.

Thanks.

![image](https://user-images.githubusercontent.com/53167314/68122521-2adb7e00-ff13-11e9-87a0-4d1bd5926c3f.png)

**Comment by waldo1001** [comment]
So .. they made a rule to force a fixed naming behaviour :-/.  Not sure I like that :(.

Thanks for the headsup - I guess I'll need to solve this by the time they release it.. .

**Comment by hmerbouche** [comment]
Hello,
It seems that the new naming rule of microsoft does not include the affix in the file name!
The new naming:
<ObjectNameExcludingPrefix>.<FullTypeName>.al
<ObjectNameExcludingPrefix>.<FullTypeName>Ext.al

Thanks

**Comment by waldo1001** [comment]
Well, I have an issue with this ... .  If I change anything on the "auto renaming" part, I will start creating new names all of a sudden in existing environments - without people expecting it .. :-/.

Don't know what I should do, to be honest :(.

**Comment by waldo1001** [comment]
@ernestasjuska , @hmerbouche ,

I decided to add a seperate tag as suggested ... .  As I don't have a complete overview - do you think this is conclusive - not sure about the controladdin :-/ - and no way I can look it up ... ?

```typescript
            case 'page': return 'Page';
            case 'pageextension': return 'PageExt';
            case 'codeunit': return 'Codeunit';
            case 'table': return 'Table';
            case 'tableextension': return 'TableExt';
            case 'xmlport': return 'XmlPort';
            case 'report': return 'Report';
            case 'query': return 'Query';
            case 'profile': return 'Profile';
            case 'pagecustomization': return 'PageCust';
            case 'enum': return 'Enum';
            case 'enumextension': return 'EnumExt';
            case 'controladdin': return 'ConAddin';
```

**Comment by waldo1001** [comment]
@ernestasjuska @hmerbouche ,

if you'd like to test it - here's a pre-build:
https://www.dropbox.com/s/7vvkwit4t9qujw9/crs-al-language-extension-1.1.20.vsix?dl=1

**Comment by waldo1001** [comment]
I think these settings should work as "Best Practice", which make you able to use a prefix (or suffix), not add it in the filename, and the pascalcasing is there ... .

```json
    "CRS.OnSaveAlFileAction": "Rename",
    "CRS.FileNamePattern": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.FileNamePatternPageCustomizations": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.ObjectNamePrefix": "ALDA ",
    "CRS.RemovePrefixFromFilename": true,

```

**Comment by hmerbouche** [comment]
@waldo1001 

I tested the new vsix and the new setting, it seems just perfect!
Do you know when you can release this new version?
Thanks

**Comment by hmerbouche** [comment]
@waldo1001 
To complete / correct your list  :)
Object | Abbreviation

Request Page | RequestPage
Control Add-ins | ControlAddin
Dotnet | Dotnet
Profile | Profile

**Comment by ernestasjuska** [comment]
@waldo1001 

Thanks. It works great.

Tested control add-ins naming:
For controladdins it should return "ControlAddIn" with capital "I".
![image](https://user-images.githubusercontent.com/53167314/68286829-6b113c80-008a-11ea-9f07-f566cd4493c5.png)

Found one more type `interface "LBC My Interface" { }` should be in file `LBCMyInterface.Interface.al`.
![image](https://user-images.githubusercontent.com/53167314/68287946-3f8f5180-008c-11ea-9e4d-2760cb728c2c.png)

**Comment by waldo1001** [comment]
Pretty soon ;-)

**Comment by DanielGoehler** [comment]
@waldo1001 Do you like to change **ConAddin** to **ControlAddin** like the [Suggestion from Microsoft](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#type-map)?

**Comment by mjmatthiesen** [comment]
Forced naming standard :( That would be the worst. The current standard isn't very readable. Gimme my spaces.
