### ISSUE TITLE
[BUG] Extend reserved keywords

### ISSUE THREAD

**Issue by fvet** [waldo1001/crs-al-language-extension#143]
Having formatted al my *.al files (5200+) I get a lot of compilation errors because of surrounding quotes getting removed on names that seem to be keywords. Tried to disable the FormatOnSave, without luck. Had to uninstall the CRS extension ...
```

field(101; "Area"; Code[10])
        {
            Caption = 'Area';
            TableRelation = Area;
        }

... Action("Actions") ...
```
is changed to

```
field(101; Area; Code[10])  // Area result in a compile error
        {
            Caption = 'Area';
            TableRelation = Area;
        }

... Action(Actions) ... // Actions result in a compile error
```

Can you please extend getAllKeywords with

- Key
- Area
- Actions
-

**Comment by waldo1001** [comment]
OOps .. closed it too early. 
I added the keywords .. will go live in a minute

**Comment by fvet** [comment]
Thanks a lot Eric!

**Comment by waldo1001** [comment]
you're welcoem - thank you for the suggestion!
