### ISSUE TITLE
Renaming Files - Which settings file is used?

### ISSUE THREAD

**Issue by aptMattKoe** [waldo1001/crs-al-language-extension#146]
Hi,

TL;DR: The "Rename Current File" function does not use the basic settings. It uses old settings from another folder. 

I'm pretty not sure if this is the correct repo to post that issue.
The "Rename" function renamed my files but with settings of an old folder settings which is not this folder. Also I have not opend it the last months.  The new folders (App and Test) did not have an settings file also also the workspace and my user has settings for CRS.
I realy want to know from where did VS Code gets the settings to rename the file.

BTW did CRS understand folder settings?

**Comment by waldo1001** [comment]
You are at the right place ;-).

I didn't change the default, indeed.  So if you rename, it will rename to the default settings ... or the settings that you have set up... .

It will take the current workspace or usersettings - whatever you have set up.  If nothing, the default.  but as said, the "default" is like Microsoft came up 2 years ago - not the currently advised setting. Reason for that is that I don't want to change behaviour just for poeple that were already using the default.  

Best is to explicitly set the setting in your settings-file...

hope that makes sense?

**Comment by aptMattKoe** [comment]
Sorry for the late response :)
Yes it makes sense. But in my case VS Code loads settings I did not know where I could find them. Not in the User, Workspace or Folder Settings file. 
I will try it again.

See you tomorrow.

**Comment by aptMattKoe** [comment]
Hi, after the TechDays it works....might be the problem of my machine.
Thanks :)
