### ISSUE TITLE
Use AL settings for "Run Current Object"

### ISSUE THREAD

**Issue by mjmatthiesen** [waldo1001/crs-al-language-extension#152]
Browsers can become a mess when connecting to a gazillion customer systems. Heck, the local credential cache can't even handle it.

Would be great if the extension was to read the AL settings and utilize them. This feature is currently useless to me because it doesn't and has no options to change the behaviour either.

![image](https://user-images.githubusercontent.com/16603906/71275001-87eb9180-2311-11ea-9b98-bf7dd43dad83.png)

Thanks and cheers and all that jazz.

**Comment by waldo1001** [comment]
I didn't even know about that setting ;-).

No promises because no idea how I would be able to do this (currently, I simply open a hyperlink).

**Comment by mjmatthiesen** [comment]
No clue how MS is doing it, but you can use node's child process exec to accomplish this.

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

There's likely other ways, maybe even some standard vs code command execute's now. I haven't browsed this codebase at all tbh.

**Comment by waldo1001** [comment]
It's indeed easier than I thought - and something I should add indeed:

apparently, this opens my blog :-)
```
chrome www.waldo.be
```

Let me see what I can do .. in what time .. but this needs to go on the agenda ;-).
