### ISSUE TITLE
Unable to add 'Extension field' to Extension List Page and Extension Card Page with designer.

### ISSUE THREAD

**Issue by Rambabu-Billuri** [waldo1001/crs-al-language-extension#156]
We are trying to add '**Extension field**' field directly to '**Extension List Page**' and '**Extension Card Page**' using designer.

Getting error, you can find in attached screens and docker logs me out. 

![Project Card](https://user-images.githubusercontent.com/57799519/76407371-42d77880-63b1-11ea-99bf-b591f422d555.png)
![Projects List](https://user-images.githubusercontent.com/57799519/76407374-43700f00-63b1-11ea-9a9d-50df80885bb7.png)
![Error](https://user-images.githubusercontent.com/57799519/76407365-41a64b80-63b1-11ea-88a9-670a3cab2913.png)

Following is the EventLog details from container.

The description for Event ID 701 from source MicrosoftDynamicsNavServer$BC cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: BC
Category: Extensions
ClientSessionId: a8845b85-6060-4234-ba2b-827d662f5639
ClientActivityId: 900ab32a-b1ed-401d-83c0-2a21dff9b87e
ServerSessionUniqueId: f515a414-164b-4652-9c4f-0f53adc0cddb
ServerActivityId: ed2fa262-a9a9-4d2d-856d-5c56b1e3866f
EventTime: 03/11/2020 09:19:54
Message The execution of the code block at HandleAddPageFieldAction had one or more unhandled exceptions., Additional info: NSDesigner
ProcessId: 9156
Tag: 00000GQ
ThreadId: 119
CounterInformation: 
CustomParameters: 00000000-0000-0000-0000-000000000000

**Comment by waldo1001** [comment]
Can you explain to me how this is related to my "crs-al-language-extension" extension?

**Comment by Rambabu-Billuri** [comment]
Please Ignore. It should be in another group.
