### ISSUE TITLE
Record Repeat snippet: Why NEXT() <1 instead NEXT() =0?

### ISSUE THREAD

**Issue by elweilando** [waldo1001/crs-al-language-extension#158]
Is there a reason why you suggest Next() <1 instead Next() =0. 
Is Next() <1 more performing?

```
Snippet: if findset repeat until (waldo's CRS AL Language Extension)
if Rec.FindSet() then begin
    repeat

    until Rec.Next() < 1;
end;
```

**Comment by waldo1001** [comment]
Well - it was thought this way to me as a good practice.
The reasoning is that you're not limited to the 0-value (which is only 1 value), but to an unlimited amount of values which are all valid.. .
