### ISSUE TITLE
Renaming files fails on codeunits that implement interfaces

### ISSUE THREAD

**Issue by nicolassaleron** [waldo1001/crs-al-language-extension#159]
Hello,

If I run the the action _Rename_ on a codeunit that implements at least one interface, a error message is raised because "File xxx does have a valid object name, it has too many quotes (")"

It can be easily reproduced:
```
interface "My Interface"
{

}

codeunit 50000 "My Codeunit" implements "My Interface"
{

}
```

**Comment by waldo1001** [comment]
Right .. sorry :(. 
I need to include interface asap - expect a solution this weekend!

**Comment by nicolassaleron** [comment]
Do not hurry, this extension rocks, this is a minor problem :)
thanks a lot for providing it

**Comment by waldo1001** [comment]
Well - it should have been there months ago ;-).

**Comment by waldo1001** [comment]
@nicolassaleron , can you try again?

**Comment by nicolassaleron** [comment]
This works:
* codeunit MyCodeunit implement MyInterface { }
* codeunit "My Codeunit" implement MyInterface { }

But this does not work:
* codeunit MyCodeunit implement "My Interface" { }
* codeunit "My Codeunit" implement "My Interface" { }

It seems that as soon as there is a double quote in the interface name, the error "too many double quotes" occurs.

I have tested on version 1.2.1
with AL Language 5.0.254558

**Comment by waldo1001** [comment]
Am I correct you have 2 objects in 1 file?  Can you share the file that doesn't work?

**Comment by nicolassaleron** [comment]
No, only one object per file :)

I have changed a little bit my object to publish the code here, but the error is still there:

```
codeunit 50000 "First Package Meth." implements "Package Assignment Method"
{
    Access = Internal;

    procedure Assign(Item: Record Item)
    begin

    end;
}
```

**Comment by nicolassaleron** [comment]
This is the error that pops:

```
File 'test.al' does not have valid object name, it has too many double quotes (")

Source : waldo's CRS AL Language Extension (Extension)
```

**Comment by TKapitan** [comment]
Hi Waldo, the problem is still the same (each object in a different file)
-----
interface "ART CU VM Machine Component Type"
codeunit 50005 "ART CU VM Comp.Type-Standalone" implements "ART CU VM Machine Component Type"
codeunit 50006 "ART CU VM Comp.Type-IncInMach" implements "ART CU VM Machine Component Type"
----

When I try to save any of those CUs I get an error 
`File 'VMCompTypeIncInMach.Codeunit.al' does not have valid object name, it has too many double quotes (")` and the file is not renamed.
