### ISSUE TITLE
Search Object Names

### ISSUE THREAD

**Issue by fvet** [waldo1001/crs-al-language-extension#160]
I gave the 'Search Object Names' command a try, but had some questions:

- It seems like you need to manually set the '.*' (Use regulare expression) parameter first before you'll to get some matches. Would be nice if the commandlet could default it?

- Seems like the search does not support 'partial' searches and and expects case matches?

![SearchObjectNames](https://user-images.githubusercontent.com/25268332/78643508-aa032280-78b4-11ea-9c50-7dd011e70a3e.gif)

_I tend to use 'Ctrl+P' a lot to find files, since our file naming still follows the object names. (or use the 'Go to Definition' to navigate to the object ... if it works)_

**Comment by waldo1001** [comment]
With v16, try using ctrl+t - that also works quite nice!

thanks for the feedback, I also notice it didn't default correctly, although I did indicate the "regex" part it in the method .. so I'm going to have a look at it again, I guess ;-).
It should be case insensitive, but I'll give it another go .. .
