### ISSUE TITLE
Renaming doesn't remove underscore

### ISSUE THREAD

**Issue by CNAPilaro** [waldo1001/crs-al-language-extension#161]
With AL 5 underscore in filenames are no longer allowed

Can you modify navobject.ts line 264+265 to
this.objectName = this.objectName.trim().toString().replace(/["_]/g, '');
this.extendedObjectName = this.extendedObjectName.trim().toString().replace(/["_]/g, '');

Regards
Christoffer

**Comment by waldo1001** [comment]
I think you meant:
```
this.objectName = this.objectName.trim().toString().replace(/["_]/g, '');
this.extendedObjectName = this.extendedObjectName.trim().toString().replace(/["_]/g, '');
```

I was a bit confused, but the "_" got removed from your message :-).

**Comment by CNAPilaro** [comment]
Seems right important thing is to remove the underscore when renaming

man. 27. apr. 2020 15.55 skrev waldo <notifications@github.com>:

**Comment by benjaminknapper** [comment]
I am unable to find documentation that outlines underscore as a forbidden character in AL file names.
Currently CRS v1.2.2 seems to me to operate in an interesting fashion as listed below.

**I have extensions:**
AL Language v5.0.254558
waldo's CRS AL Language Extension v1.2.2

**Settings:**
CRS: Object Name Prefix = XX_
CRS: On Save Al File Action = Rename

**Original file name:**
Pag46-Ext50131.XX_SalesOrderSubform.al

**New file name upon saving:**
Pag46-Ext50131.XX_XXSalesOrderSubform.al

**Object header:**
pageextension 50131 "XX_SalesOrderSubform" extends "Sales Order Subform" //46

So my two questions are:
1) @CNAPilaro or @waldo1001 can you point me towards the documentation that outlines underscore as a forbidden character in AL file names? I want to be able to justify the work this will require to remove the underscores we have appended as our prefix.
2) Regardless of the validity of the underscore character in files names. @waldo1001 is the above the desired effect of the rename function for files that already exist and have been using your extension?

**Comment by waldo1001** [comment]
it is not the desired effect - just a consequence of me removing underscores.
I'm doing a build now that fixes it, and that introduces a setting where you can control it however you want.

about documentation: I haven't. but the Code Analysis indicate it
![image](https://user-images.githubusercontent.com/12088142/80509530-d83ac600-8979-11ea-8348-e8ad729b3f12.png)

**Comment by benjaminknapper** [comment]
I appreciate the speedy response. I also wanted to note that after I posted my comment I found Issue #169 and wanted to put that here!

You're the best!
