### ISSUE TITLE
TypeError: Cannot read property 'document' of undefined

### ISSUE THREAD

**Issue by stefanoPrimo** [waldo1001/crs-al-language-extension#163]
```
TypeError: Cannot read property 'document' of undefined
	at Object.toggleRunObjectFromStatusBar (c:\Users\Dev\.vscode\extensions\waldo.crs-al-language-extension-1.2.1\out\UI\CRSStatusBar.js:7:54)
	at HandleOnOpenTextDocument (c:\Users\Dev\.vscode\extensions\waldo.crs-al-language-extension-1.2.1\out\CRSFunctions.js:156:18)
```
maybe adding:
```
	if(!vscode.window.activeTextEditor)
		return;
```

before 
`    let currentfile = vscode.window.activeTextEditor.document.uri;`

can solve the issue.

It happens when I open the pages of the extension that are virtual (eg. with git temporal)

**Comment by waldo1001** [comment]
I would like to repro this scenario, but I don't understand when it happens.. .  Can you elaborate on that?

**Comment by stefanoPrimo** [comment]
Hi,
try this:
open the Developers tools of Vscode, then open any virtual page like using the command `AZ AL Dev Tools: Show Code Analyzers Rules`

now you will see an error in the developer tools' console

**Comment by waldo1001** [comment]
I try that - but I don't see the error anywhere.. ?

**Comment by waldo1001** [comment]
Sorry - I can't repro this .. please open the issue again if the problem persists, and you have a repro scenario.
