### ISSUE TITLE
New snippet - interface enhancement

### ISSUE THREAD

**Issue by TKapitan** [waldo1001/crs-al-language-extension#165]
Hi Waldo,
I have two possible enhancements for interfaces

1. Snippet for interface procedure (just to generate the same thing as a procedure but without begin/end)
2. New quickfix to generate the body of CU that implements an interface (with all procedures). In my current project, I have already 6 interfaces for enums and this is one of the things that I really miss

**Comment by TKapitan** [comment]
![image](https://user-images.githubusercontent.com/37966300/79617165-1e389400-8107-11ea-98e9-a3b812eee50e.png)

**Comment by waldo1001** [comment]
If you make the snippet, I'll add it ;-).  Or an example of code?

the quickfix is something I can't do - but may be a good suggestion for this extension:
https://marketplace.visualstudio.com/items?itemName=davidfeldhoff.al-codeactions
