### ISSUE TITLE
if/then statement runs tcodeunit snippet

### ISSUE THREAD

**Issue by TKapitan** [waldo1001/crs-al-language-extension#166]
Hi,
![image](https://user-images.githubusercontent.com/37966300/79618032-3f9a7f80-8109-11ea-8be8-a27c5d73616c.png)

The if/then statement runs tcodeunit snippet (I wrote if, then wrote some characters from the function name, selected the one I wanted, wrote then, space - and then I want to go to the new line, but the snippet inserts codeunit.

**Comment by TKapitan** [comment]
And maybe the same problem with :
![image](https://user-images.githubusercontent.com/37966300/79643753-b3d63100-81a4-11ea-9a3c-475d771c2b7f.png)

**Comment by waldo1001** [comment]
hm, will see what I can do about that ... .
