### ISSUE TITLE
CRS.ObjectNameSuffix adds Suffix in procedures to objects parameters if procedure name ends with "action"

### ISSUE THREAD

**Issue by elweilando** [waldo1001/crs-al-language-extension#168]
If you use a procedure in a page extension which name ends with "action", the suffix will be added to the parameter if the expected parameter is an object.

Codeunit
```
    procedure MyProcedureNameEndsWithaction(var test: Record "Sales Header")
    begin

    end;
```

Page Extension Before Saving
```
    trigger OnOpenPage()
    var
        TestCodeunit: Codeunit "Testcodeunit SUFFIX";
    begin
        TestCodeunit.MyProcedureNameEndsWithaction(Rec);
    end;
```

Page Extension After Saving
```
    trigger OnOpenPage()
    var
        TestCodeunit: Codeunit "Testcodeunit SUFFIX";
    begin
        TestCodeunit.MyProcedureNameEndsWithaction("Rec SUFFIX");
    end;
```

**Comment by waldo1001** [comment]
I will look at it - but these are insanely complex (for me ..) regex I have to deal with.

The problem here is the combinartion "page" object type and the word "action" .. which will indeed add suffixes.  I hope I can narrow it down thanks to this example...

**Comment by waldo1001** [comment]
meanwhile - please don't end your proc names with "action" ;-)
