### ISSUE TITLE
Unexpected file renaming after update

### ISSUE THREAD

**Issue by TroelsMuffThygesen** [waldo1001/crs-al-language-extension#169]
Hi
After your latest update of this extension we are experiencing unexpected file remaning even though we have not changed the extension setting for our AL project. 
When we modify an existing file previously called "Vault Management.al" (originally named by this extension) it is suddently remaned to "Vault ManagementEVAS.al". The object in the file is codeunit 50026 "Vault Management_EVAS".

The settings file in the repository is like this and it has been working fine until today.
![image](https://user-images.githubusercontent.com/64460327/80457034-e57e9300-892e-11ea-9ca7-316cb4655e6f.png)

I can see from the change log that you updated something regarding removal of underscores, and as you can see from our settings fil our suffix includes a suffix so perhaps you remove underscores before suffixes, and then the RemoveSuffixFromFilename setting cannot be carried out as you cannot find the complete suffix anymore.

Hoping for a quick hotfix
Troels Thygesen

**Comment by waldo1001** [comment]
Hi Troels,

I'll look at it.  Sorry about this -  didn't think of this scenarios (I have 72 cases that I test every compile ;-) - now I will have 73 ;-)).

**Comment by waldo1001** [comment]
I have a solution - it introduces a new setting "RemoveUnderscoreFromFilename", which is default to true.  The removal of "_" has been redone... .
Will be released late today...
