### ISSUE TITLE
action indentation

### ISSUE THREAD

**Issue by Petyun** [waldo1001/crs-al-language-extension#170]
Hi, after last update of CRS (1.2.3 - 2020-04-28) on saving al file I see it changed indentation for action():
![CRS_Action](https://user-images.githubusercontent.com/22754447/80588846-c6146280-8a21-11ea-8750-cb8dd1b32e1b.PNG)

**Comment by waldo1001** [comment]
Oh no :(.
Thanks for mentioning .. I didn't notice this.

**Comment by waldo1001** [comment]
Shoud be fixed now (version 1.2.4) 🤞🤞
