### ISSUE TITLE
Reorganize / Rename Symbols did not "rename Symbols"

### ISSUE THREAD

**Issue by InnoNavSupport** [waldo1001/crs-al-language-extension#173]
Like you mentioned in your blog, it is just not possible yet.
Will it be possible in the near future?
Because of the converted AL-Objects it would be very nice to use your function without braking the code.

Thanks and already great Job done!

Daniel

![image](https://user-images.githubusercontent.com/62563638/80944297-7ea72100-8de9-11ea-91ce-cbceacf16a92.png)

**Comment by waldo1001** [comment]
Well, I've spent quite some time trying to figure out how I could do that - and it's not that easy. 

Can you elaborate a bit more on the reason why this would be interesting (repeatably) for you?

**Comment by InnoNavSupport** [comment]
We have converted our code to AL and now we want to use your rename functionality to add a suffix to our objects. But The rename changes the symbol name without changing the references. So all the references are lost and all the referencing objects have to be fixed manually.

**Comment by waldo1001** [comment]
Thanks.

Well .. There is nothing I can do about that, I'm afraid, except for complete rebuild the prefix-suffix-functionality, which is now a regex-find/replace.  It's meant for continuous development (and not forgetting prefix/suffix - and not for a one-time-provide-prefix/suffix.. .

However, with some clever find/replace with the explorer, you should be able to "fairly quickly" perform all corrections in code .. that's how I did it..

**Comment by InnoNavSupport** [comment]
Thanks!
