### ISSUE TITLE
Suggestion: Insert All Fields

### ISSUE THREAD

**Issue by jhoek** [waldo1001/crs-al-language-extension#174]
In VS code, with a page object (with a source table) open in the active editor (and possibly with the caret inside a repeater) I would like to have a command in the command palette to insert all fields from the source table into the page. In some scenarios, removing a few irrelevant fields is a lot less work then adding each field to the page individually.

A bit like the old Field Menu in C/SIDE, I guess...

**Comment by anzwdev** [comment]
This is the functionality that I've added to my 'AZ AL Dev Tools/AL Code Outline' extension long time ago. It shows 'Add multiple fields' code action when you click on repeater or group on a page. Have you tried to use it?

**Comment by jhoek** [comment]
No, but I certainly will! Thx! :-)

**Comment by waldo1001** [comment]
I was going to answer this issue - but thanks @anzwdev  for keeping a close look to my issues as well ;-)
