### ISSUE TITLE
Filename conventions Microsoft vs CRS extension

### ISSUE THREAD

**Issue by louagej** [waldo1001/crs-al-language-extension#176]
Hi,

According the crs-extension, the default naming convention of a `.al` file is:  `<ObjectTypeShort><ObjectId>.<ObjectNameShort>.al`
When I enabled CodeCop in my project, I received a warning that my filename isn't according the conventions.:

`The file ... has an incorrect name. The valid name is MyCodeunit.Codeunit.al.AL(AA0215)`

![image](https://user-images.githubusercontent.com/7229592/85130584-7be77a80-b235-11ea-8bad-32c1dc83e36c.png)

According the Microsoft best practices, [File naming examples](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming-examples), I find out that this should be: `<ObjectName>.<ObjectType>.al`

![image](https://user-images.githubusercontent.com/7229592/85130876-05974800-b236-11ea-8a52-cc282362e1e6.png)

I can change this in the setting, but the space in the object name isn't removed.
![image](https://user-images.githubusercontent.com/7229592/85131128-835b5380-b236-11ea-9754-7b1c531f687f.png)

Can the crs-extension removes spaces from the filename trough setup?

Kind regards,
Job

**Comment by pjllaneras** [comment]
Good point.

Following with Microsoft Conventions:

![image](https://user-images.githubusercontent.com/1036673/85453267-ff89ca00-b59b-11ea-963c-dc5ea69aaaa5.png)

If I create the pattern

`    "CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectType>.al"`

A page extension will be renamed to "objectname.pageextension.al"

If I change the pattern to

`    "CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShort>.al"`

A page extension will be renamed to "objectname.pag.al"

But "Al Language" wants the name: "objectname.PageExt.al"

The same applies to table extensions.

It would be greate that we can rename following MS filename conventions.

**Comment by waldo1001** [comment]
Does this help?
https://www.waldo.be/2020/04/03/how-to-really-rename-all-al-files-of-your-business-central-app/
:-)

These settings *should* make sure you follow Microsoft's file name convention:

```json
    "CRS.FileNamePattern": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.FileNamePatternPageCustomizations": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
    "CRS.OnSaveAlFileAction": "Rename",
    "CRS.RenameWithGit": false,
    "CRS.ObjectNameSuffix": " WLD",
```

**Comment by pjllaneras** [comment]
Ooohhhhh Yeahhhh!!! That is!!! ObjectTypeShortPascalCase is what I need. Thanks a lot!!!

**Comment by louagej** [comment]
Hi @waldo1001 

Thanks a lot!

I could have checked [your post](https://www.waldo.be/2020/04/03/how-to-really-rename-all-al-files-of-your-business-central-app/) before creating this issue :disappointed:

:bulb: maybe these setting can set as default with the extension.

Kind regards,
Job

**Comment by waldo1001** [comment]
It has been asked before to make it default .. thing is .. I might change behaviour that way, so I'm not sure about that :(.
