### ISSUE TITLE
Fix Page Extension Abbreviation

### ISSUE THREAD

**Issue by pantifas21** [waldo1001/crs-al-language-extension#185]
Hi Waldo,

Could you fix the page extension abbreviation in your extension?
I'm getting advice with the CodeCop analyzer because the "Best Practices" indicates that correct abbreviation is PageExt, not PagExt.

Thanks!

![image](https://user-images.githubusercontent.com/38859156/102780888-018be480-4397-11eb-9d3a-6ab8cc412f0f.png)

Source: https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-bestpracticesforalcode#file-naming

**Comment by waldo1001** [comment]
Hi, 

can you check your settings? (user, and workspace) to look at the patterns for extension objects?  

My default should be correct:
![image](https://user-images.githubusercontent.com/12088142/102784432-af4dc200-439c-11eb-882c-a8d30a6f6aad.png)

so the only reason why I see that it's giving that, are your settings.. .

**Comment by pantifas21** [comment]
Hi,
this are my settings
![image](https://user-images.githubusercontent.com/38859156/102885133-2d6ca000-4453-11eb-9abf-5c500f99502f.png)
I'm using <ObjectTypeShort> and I'm getting PagExt 

What tag I should use for the correct abbreviation?

Thanks!

**Comment by waldo1001** [comment]
If you remove all three, it should give you the recommended settings for Microsoft...
