### ISSUE TITLE
build/publish for 'run current object'

### ISSUE THREAD

**Issue by TheDenSter** [waldo1001/crs-al-language-extension#186]
Not an issue but a feature suggestion. Right now you have to build/publish the app before you can 'run current object', it would be cool if that were part of the process. Maybe have two commends - one with run with and one without.

**Comment by waldo1001** [comment]
Done!
![image](https://user-images.githubusercontent.com/12088142/104138276-57a2e500-53a3-11eb-9210-13ff9058c2f2.png)

**Comment by TheDenSter** [comment]
It works! Awesome! It only opens two browser tabs

**Comment by waldo1001** [comment]
that's because the normal publish opens one as well.. .

besides this setting (which doesn't seem to work for me):
![image](https://user-images.githubusercontent.com/12088142/104155421-76c36600-53e7-11eb-8da3-e566ca5dbb60.png)
there is nothing much to do about that :(.

**Comment by waldo1001** [comment]
I decided to use the "publish without debugging" - as that seems to take that "launchbrowser" setting in launch.json into account .. . Don't forget to set that, though ;)

**Comment by TheDenSter** [comment]
I was going to suggest that, although it would be good to have the option to launch it with the debugger.

The browser is launched when I use F5 whether I have that setting or not, it only seems to work for publish without debugging. 

Thanks dude!!

**Comment by wbrakowski** [comment]
Hey waldo,

this does not seem to work for me. Both of these commands:
![image](https://user-images.githubusercontent.com/53928639/106860550-d817e580-66c4-11eb-928c-193ef1ae0eb2.png)

...open the browser in my role center, not in the object i am currently in.

Notes: 
- I published the object before
- I try to run a report
- launchbrowser is set to "false"

This is my folder structure:
![image](https://user-images.githubusercontent.com/53928639/106860729-101f2880-66c5-11eb-92e1-744f10efef7f.png)

Anything else I have to consider to make this work?

Thank you.

**Comment by waldo1001** [comment]
Hi Waldemar,

I seem to have the same problem - with Chrome .. 

Can you try with Edge?
![image](https://user-images.githubusercontent.com/12088142/106877864-90e81f80-66d9-11eb-841c-9bc0b4ad8a3f.png)

When I simulate this with chrome, I have the same issue :(.
![image](https://user-images.githubusercontent.com/12088142/106877922-a3625900-66d9-11eb-8d8a-5d168ba65a9d.png)

**Comment by wbrakowski** [comment]
Hi waldo,

Edge works fine. 
I am not going to use it, but at least now i know that this is a known problem :-)

Thank you.
