### ISSUE TITLE
Snippet for Installation Codeunit

### ISSUE THREAD

**Issue by wbrakowski** [waldo1001/crs-al-language-extension#188]
Hey waldo,

would it be possible to include a snippet for an installation codeunit in your extension?
Something like this:
```al
codeunit 50100 MyInstallCodeunit
{
    Subtype=Install;

    trigger OnInstallAppPerDatabase();
    var
        myAppInfo : ModuleInfo;
    begin
        NavApp.GetCurrentModuleInfo(myAppInfo); // Get info about the currently executing module

        if myAppInfo.DataVersion = Version.Create(0,0,0,0) then // A 'DataVersion' of 0.0.0.0 indicates a 'fresh/new' install
            HandleFreshInstall
        else
            HandleReinstall; // If not a fresh install, then we are Re-installing the same version of the extension
    end;

    local procedure HandleFreshInstall();
    begin
        // Do work needed the first time this extension is ever installed for this tenant.
        // Some possible usages:
        // - Service callback/telemetry indicating that extension was installed
        // - Initial data setup for use
    end;

    local procedure HandleReinstall();
    begin
        // Do work needed when reinstalling the same version of this extension back on this tenant.
        // Some possible usages:
        // - Service callback/telemetry indicating that extension was reinstalled
        // - Data 'patchup' work, for example, detecting if new 'base' records have been changed while you have been working 'offline'.
        // - Setup 'welcome back' messaging for next user access.
    end;
}
```

**Comment by waldo1001** [comment]
That's a good idea.
I'll put it on the todo-list. ;-).
If you need it fast - could could of course create a PullRequest ;-).

**Comment by ajkauffmann** [comment]
I would also suggest to look at upgrade tags. Only using versions to install / upgrade can become complex for larger or widely-used apps.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-upgrading-extensions#using-upgrade-tags-to-control-upgrade-code

**Comment by waldo1001** [comment]
I get that .. but .. 

this is for install, not upgrade.  Install only gets executed when:
- you install an app for the first time
- you uninstalled it, and reinstall it again (same version)
So .. code doesn't change, but install-code does run again.

In terms of "installation", that's all we need to know to see what we need to do.

using upgrade tags in install-scenario isn't really necessary, in my opinion.  
For any next version (= upgrade), it's absolutely necessary.  I actually created internal snippets for that .. would this be interesting for the community as well?

upgrade codeunit:
![image](https://user-images.githubusercontent.com/12088142/104700326-45fb6d80-5714-11eb-9ee2-21cf54b16a3f.png)

Move table procedure:
![image](https://user-images.githubusercontent.com/12088142/104700379-5a3f6a80-5714-11eb-994d-1a719b569fc0.png)

Move field procedure:
![image](https://user-images.githubusercontent.com/12088142/104700401-64f9ff80-5714-11eb-9885-d83de4250dc2.png)

**Comment by ajkauffmann** [comment]
Oh yes, it is necessary for install. During an install you need to initialize the upgrade tags that this version already includes.

Not everybody starts with version 1 of an app. If somebody starts (fresh install) with version 3, which already had some upgrades managed by upgrade tags, then you need to set those upgrade tags as if they were already done.

**Comment by waldo1001** [comment]
Ok, but that's "setting" upgrade tags, not creating a new one just because of an install-codeunit ;-).
So, in case I don't have ANY upgrade tag/codeunit .. I don't have anything to "manage" during my install.. .  So .. again .. why would I add it in my install snippet?

Maintaining upgrade-tags during install is part of the upgrade-pattern, not the install-pattern.. .  So I wouldn't "just" add it to the install-snippet.  Just my 0.02€.  Having something in another snippet - fine.  Having 2 install-snippets .. also fine.  I'm open to anything ;-).

That said - I'm quite sure that many people forget that part.. .  You might have a blogpost on your hands there ;-)

**Comment by ajkauffmann** [comment]
Yes, the creating the upgrade tag comes first, which is an upgrade pattern.  But then you need to add it to the install codeunit as well. Simple solution, just add

`UpgradeTag.SetAllUpgradeTags()`

to the install snippet and you're done.

**Comment by waldo1001** [comment]
Ok, I'll add it - it's better to add it in two install codeunits, than to forget it .. so .. 🤷‍♂️
