### ISSUE TITLE
Auto-rename support for Report Extensions

### ISSUE THREAD

**Issue by martonsagi** [waldo1001/crs-al-language-extension#189]
Just a reminder for BC18: auto-rename obviously fails for report extensions. :)

![image](https://user-images.githubusercontent.com/18100709/106261694-31de6280-6222-11eb-9446-a91d6f227014.png)

![image](https://user-images.githubusercontent.com/18100709/106261614-12dfd080-6222-11eb-94c2-798117dfd72e.png)

**Comment by waldo1001** [comment]
You're right - it shouldn't be too much work.

Do you know what the default abbreviation is?

**Comment by martonsagi** [comment]
Nope, the insider build has no report extension object by default. Documentation has not been updated yet: https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/blob/live/dev-itpro/compliance/apptest-bestpracticesforalcode.md

My best guess would be `ReportExt`, maybe?

**Comment by waldo1001** [comment]
That's my guess as well .. .  I did the changes, but need to include tests now ;-).

**Comment by waldo1001** [comment]
Should work now!
