### ISSUE TITLE
Search Microsoft Translation (similar to Search: Microsoft Docs)

### ISSUE THREAD

**Issue by wbrakowski** [waldo1001/crs-al-language-extension#190]
Hey waldo,
I was working on a small translation extension recently but decided to drop it because Marton is working on a translation feature in his AL Studio. I already built one function that is very similar to your "Search: Microsoft Docs" function. You can search for a translation using [this microsoft service](https://www.microsoft.com/en-us/language/Search?&searchTerm=sachkonten&langID=354&Source=false&productid=0).

Do you think this might be useful for your CRS extension?
If yes, I could create a pull request in the next weeks.

Check this gif where I show the functionality:

![ShowTranslation](https://user-images.githubusercontent.com/53928639/106435659-76147180-6473-11eb-955d-2aba3547f31a.gif)

Kind regards,
Waldemar

**Comment by waldo1001** [comment]
Hey Waldemar,

It can sure be useful of course.   I can already see a few use cases.. .  And I would welcome it with open arms 😉.

But you’ve got your “AL Navigator”, don’t you?  Why not put it in that one? 😉.

Kind regards,

Eric “waldo” Wauters

[cid:image004.png@01D6F978.6284CB30]

[cid:image003.png@01D6F977.FB0A9ED0]
E:   me@waldo.be<mailto:me@waldo.be>
S:   Twitter<https://twitter.com/waldo1001> | LinkedIn<https://www.linkedin.com/in/ericwauters/>
W:   www.waldo.be<http://www.waldo.be/>

**Comment by wbrakowski** [comment]
Hey waldo,
I've thought about it again.
Probably it will make more sense to put it in my AL Navigator.
Sorry for the nonsense issue. 

Kind regards,
Waldemar

**Comment by waldo1001** [comment]
Looking forward to it!
