### ISSUE TITLE
null file

### ISSUE THREAD

**Issue by RichardSykora** [waldo1001/crs-al-language-extension#194]
Hi,

it looks like that your extension is creating a "null" file, and this file contains my network share to my server. To make sure which extension is  generating the file, i deleted all the vscdoe folders, and installed only AL Language and this extension. 
When i uninstall your exteandion, and delete the null file, everything is fine, after reinstalling your extension, it creates the file again

Hope you can fix it soon :)

kind regards
richard

**Comment by waldo1001** [comment]
I can have a look at it if you give me a decent repro scenario ... but at this point, I have no idea 🤷🏻‍♂️ ..

Demo repo, settings, anything you can share that reproduces this problem ...

Sent from my iPhone

On 16 Feb 2021, at 18:56, RichardSykora <notifications@github.com> wrote:

﻿

Hi,

it looks like that your extension is creating a "null" file, and this file contains my network share to my server. To make sure which extension is generating the file, i deleted all the vscdoe folders, and installed only AL Language and this extension.
When i uninstall your exteandion, and delete the null file, everything is fine, after reinstalling your extension, it creates the file again

Hope you can fix it soon :)

kind regards
richard

**Comment by RichardSykora** [comment]
it already happens, when i start a new projekt with AL: Go!
![image](https://user-images.githubusercontent.com/49237360/108112645-ae809600-7096-11eb-9f8c-5c5248cd3813.png)

when i disable your extension, and do the same again, everything is ok

This are my installed extensions:
![image](https://user-images.githubusercontent.com/49237360/108112743-d07a1880-7096-11eb-9ab0-0015848afe86.png)

If you want we can start a teams or teamviewer session

**Comment by waldo1001** [comment]
I can't repro this, I'm sorry .. so I can't see what's there to fix :-/.

**Comment by RichardSykora** [comment]
Hi,

i have found the problem now, the issue was in my powershell 7 profile. Since i rarly use powershell 7, i didnt realize, that there was an error. Are you loading this profile?

Anyways, you can close this issue
Thanks a lot

**Comment by waldo1001** [comment]
Aight, thanks!

I'm not loading any profile ..
