### ISSUE TITLE
Interested to demo your extension in a joined Areopa webinar?

### ISSUE THREAD

**Issue by lvanvugt** [waldo1001/crs-al-language-extension#197]
Hi Eric

Are you interested in demoing your VSCode extension in a [Areopa](https://areopa.academy/) webinar?
The idea is to have AL VSCode extension domed to the community.

If you're interested please let me know. Mail to: webinars@areopa.academy.

b rg
Luc van Vugt

P.S.: ik zet dit bericht op alle repos van AL VScode extensies.

**Comment by christianbraeunlich** [comment]
This issue can also be closed as @waldo1001 has successfully demonstrated: https://www.youtube.com/watch?v=GJa9hh-MejE&t=23m24s
