### ISSUE TITLE
File name for pagecustomization

### ISSUE THREAD

**Issue by TheDenSter** [waldo1001/crs-al-language-extension#199]
The filename for page customizations does not follow my setting:
![image](https://user-images.githubusercontent.com/23434319/115418088-0b3f2080-a1ae-11eb-90d4-0f74bbf436ff.png)

**Comment by waldo1001** [comment]
Did you set this?
![Uploading image.png…]()

**Comment by waldo1001** [comment]
The reason for the separate setting is the fact that the original requirement differed from the extension-objects 🤷‍♂️

**Comment by TheDenSter** [comment]
Now I did, and it works :) thanks dude, you're awesome.
