### ISSUE TITLE
¿Cómo cambio el patrón que genera los archivos en Waldo CRS para que se escriban de la manera que yo quiero?

### ISSUE THREAD

**Issue by Nuevo207** [waldo1001/crs-al-language-extension#200]
Buenas.

Necesito cambiar el patrón de escritura que genera automáticamente los archivos en Waldo CRS. No se cómo hacerlo. ¿Alguien me puede explicar cómo hacerlo?

Gracias.

**Comment by waldo1001** [comment]
Hi,

you can change the file patterns in settings:

```json
...
    "CRS.FileNamePattern": "...",
    "CRS.FileNamePatternExtensions": "...",
    "CRS.FileNamePatternPageCustomizations": "...",
...
```

may be this is a good blogpost for you:
https://www.waldo.be/2020/04/03/how-to-really-rename-all-al-files-of-your-business-central-app/

**Comment by Nuevo207** [comment]
Gracias, por la información. Pero, ¿cómo entro en la configuración de Waldos para poner los parámetros que has puesto?

**Comment by waldo1001** [comment]
This is just VSCode settings.

More info:
https://code.visualstudio.com/docs/getstarted/settings

**Comment by waldo1001** [comment]
Can I ask to please use "Google Translate" and enter your questions in English?
https://translate.google.com/

**Comment by Nuevo207** [comment]
Yes. Sorry.

**Comment by Nuevo207** [comment]
Is there a video where you can teach me how to do it? change the pattern of waldo crs settings

**Comment by waldo1001** [comment]
Not yet .. but on June 1st, I will do a session on this extension.

It's really simple: just read the links I gave above..
