### ISSUE TITLE
CRS: Compile DGML

### ISSUE THREAD

**Issue by louagej** [waldo1001/crs-al-language-extension#202]
Hi Waldo,

As you mentioned in you blog [DGML Dependency](https://www.waldo.be/2021/05/11/a-somewhat-easier-way-to-generate-a-dgml-dependency-graph-of-your-business-central-extensions/) I'm trying to use the command `Compile DGM`

![image](https://user-images.githubusercontent.com/7229592/119481120-a64d8c00-bd52-11eb-80e6-2397d7d92438.png)

But I'm facing this error:
```log
C:\Users\Job Louage\.vscode\extensions\ms-dynamics-smb.al-7.1.453917\bin\alc.exe /project:undefined /packagecachepath:undefined./.alpackages /generatecrossreferences

'C:\Users\Job' is not recognized as an internal or external command, operable program or batch file.
```

**Comment by waldo1001** [comment]
You need a real workspace where you can compile an AL app.
And - you need one active document open when compiling (for it to figure out the right workspace).

You can "just" open a folder - it would take just all apps in that folder.

**Comment by louagej** [comment]
Hi Waldo,

Thanks for the info but I tried the command within a workspace and with a folder (both with a .al file opened).
Both outputs where the same error:
```log
C:\Users\Job' is not recognized as an internal or external command, operable program or batch file.
```
I guess it has something to do with the path, since my username has a space in it.
The messages just shows my `first name`.

**Comment by waldo1001** [comment]
ah .. ok.
I created an update - can you check (1.4.7)

**Comment by louagej** [comment]
Hi Waldo,

in the `src/CRSTerminal.ts` you already fixed:
```typescript
    Terminal.sendText(`${alcpath} /project:${projectpath} /packagecachepath:${packagecachepath} /generatecrossreferences`);
}
```

towards:
```typescript
    Terminal.sendText(`${alcpath} /project:"${projectpath}" /packagecachepath:"${packagecachepath}" /generatecrossreferences`);
}
```

But can you also fix the ${alcpath}?

```typescript
    Terminal.sendText(`"${alcpath}" /project:"${projectpath}" /packagecachepath:"${packagecachepath}" /generatecrossreferences`);
}

**Comment by waldo1001** [comment]
Ok, it was not *that* easy, apparently, but the latest (v1.4.9) might work...

**Comment by louagej** [comment]
Hi Waldo,

a complete different message now:

```log
C:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App>$Temp = Get-Location
'$Temp' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App>Set-Location "C:\Users\Job Louage\.vscode\extensions\ms-dynamics-smb.al-7.1.453917\bin"
'Set-Location' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App>./alc.exe /project:"c:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App" /packagecachepath:"c:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App./.alpackages" /generatecrossreferences
'.' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Job Louage\al\Top\Warehouse API\Warehouse_API_App>Set-Location $Temp
'Set-Location' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by waldo1001** [comment]
Dear god... .  I can't get this working properly.  The terminal isn't PowerShell in your case... :(

**Comment by louagej** [comment]
Hi,

indeed, this is a crs terminal:

![image](https://user-images.githubusercontent.com/7229592/119501371-1961fd00-bd69-11eb-9edf-e5f009d17cca.png)

**Comment by waldo1001** [comment]
Yeah, but for some reason, it's a cmd, not "PowerShell".  
I'm merely opening a terminal.  Assuming it's PowerShell that will be opened.. .
