### ISSUE TITLE
Exclude specific fields from adding prefix/suffix

### ISSUE THREAD

**Issue by Lazys** [waldo1001/crs-al-language-extension#211]
We need to exclude some fields from adding prefix/suffix. I have two examples:
1. New fields regarding Global Dimensions - we need to stick to the MS fields naming convetion ("Shortcut Dimension.."), because if we add our suffix to that field it will be skipped during standard changing global dimensions functionality.
2. MobileNav ISV extensions - we're adding new pages/page extensions where we need to add field "FieldControl" and that name cannot change. We cannot add our suffix there, becuase it won't work.

Can we specify somehow which fields should be skipped by our extension? Some kind of pragma directive would be awesome for such scenarios.

**Comment by waldo1001** [comment]
Will be part of next release!
