### ISSUE TITLE
Snippet for LogMessage any good?

### ISSUE THREAD

**Issue by christianbraeunlich** [waldo1001/crs-al-language-extension#236]
I think it's still a challenge to use the `LogMessage(...)` method because it contains so many parameters. Maybe a snippet could be used to make developers want to use it more?

Once implemented, it will be copied and adapted more often I believe.

Not sure if this reflects the real world... let's discuss 🦦

**Comment by waldo1001** [comment]
For sure!  Good idea!

tLogMessage would make sense!
