### ISSUE TITLE
Command 'CRS: Rename - Current File' resulted in an error (command 'crs.RenameCurrentFile' not found)

### ISSUE THREAD

**Issue by MBK75** [waldo1001/crs-al-language-extension#245]
Hello,

Today some of my VS Code projects have been failing with the error mentioned in the title ("...command ... not found").  When I look at the console in VS Code, I see the following:

mainThreadExtensionService.ts:111 Activating extension 'waldo.crs-al-language-extension' failed: Cannot find module 'opn'
Require stack:
- c:\Users\matt_\.vscode\extensions\waldo.crs-al-language-extension-1.5.9\out\DynamicsNAV.js
- c:\Users\matt_\.vscode\extensions\waldo.crs-al-language-extension-1.5.9\out\CRSFunctions.js
- c:\Users\matt_\.vscode\extensions\waldo.crs-al-language-extension-1.5.9\out\extension.js
- c:\Users\matt_\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\matt_\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\matt_\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js.

Is there an "opn" extension I need to install from somewhere?

**Comment by MBK75** [comment]
I installed the previous version (I had a new one that installed 6 hours ago), and it is working again.  Perhaps an issue in the latest version?

**Comment by christianbraeunlich** [comment]
Thanks @MBK75 for reporting this bug and sorry about the mess. What is interesting for me is the fact that there is no compilation error.

Hint for the future: the opn dependency is deprecated (https://www.npmjs.com/package/opn) and has been replaced by open (https://www.npmjs.com/package/open).

**Comment by waldo1001** [comment]
thanks for reporting indeed!

Just upgraded opn to open .. and implemented your fix as well.

All seems well again.  Can you confirm, @MBK75 ?

**Comment by MBK75** [comment]
Thank you! I have not tried yet but will
