### ISSUE TITLE
Object Name Prefix breaks all reports on save

### ISSUE THREAD

**Issue by matthias-planzer** [waldo1001/crs-al-language-extension#252]
I had to remove the Setting "Object Name Prefix", as it currently breaks all Reports.
When I want to compile the app on save, it fails with the error "The name '{0}' cannot be used as an identifier because it does not comply with the Common Language Specification" (al379)
This is being caused by the fact that the prefix contains a space, which is not allowed in Report Columns.
It would be great if there was a way to disable this feature at all in Reports, as we have some Word Reports, where renaming of the fields in the layout takes forever, as there is no simple "search + replace" option like there is in RDLC reports.

**Comment by waldo1001** [comment]
Fixed in next release!
