### ISSUE TITLE
CRS: Reorganize - Current File is always adding a prefix in Report Extensions

### ISSUE THREAD

**Issue by frobiii** [waldo1001/crs-al-language-extension#253]
Hi waldo,

with v15.5.16 there is bug with CRS: Reorganize - Current File  and / or automatic saving in report extensions. Whenever the command is executed, the prefix is added again.
The prefix must be set up with a space at the end „PTE “ . Because no spaces are allowed in extended report column names, the space is removed. When you save the file again the prefix doesn't find a match because it searches including the space and adds the prefix again without space.

It would be great if you could fix this for us.

Thank you very much.

![image](https://user-images.githubusercontent.com/46748244/177980145-7e4b603b-5c34-4ae7-a5b4-1eef8044a4e3.png)

**Comment by waldo1001** [comment]
This keeps haunting me :(

**Comment by waldo1001** [comment]
Thanks for reporting - fix underway!
