### ISSUE TITLE
ReportExtension prefixes not working in columns when ObjectNamePrefix contains a space

### ISSUE THREAD

**Issue by deerware** [waldo1001/crs-al-language-extension#263]
Hi,

Our ObjectNamePrefix contains a space, because we need to distinguish our global and customer projects, our current settings are:
```json
"CRS.ObjectNamePrefix": "ART CU ",
"CRS.OnSaveAlFileAction": "Rename",
```

A problem unfortunately comes with ReportExtensions, it does not format correctly when it comes to spaces.
```al
column(ART_CU_Quote_SalesHeaderCaption; QuoteLbl) { }
```
becomes
```al
column("ARTCU ART_CU_Quote_SalesHeaderCaption"; QuoteLbl) { }
```

I could understand that, but even if we were to use the `ARTCU` instead of `ART_CU`, <ins>**it still doesn't work** because it doesn't recognize it's own formatting</ins> and just loops around, and the name is changed with each save, like so:
```al
// After 2nd save
column(ARTCUART_CU_Quote_SalesHeaderCaption; QuoteLbl) { }

// After 3rd save
column("ARTCU ARTCUART_CU_Quote_SalesHeaderCaption"; QuoteLbl) { }

// After 4th save
column(ARTCUARTCUART_CU_Quote_SalesHeaderCaption; QuoteLbl) { }

// After 5th save
column("ARTCU ARTCUARTCUART_CU_Quote_SalesHeaderCaption"; QuoteLbl) { }

// And so on..
```

I would propose that multiple accepted prefixes could be set, with the default being the first one, or, better yet, just don't do anything if the prefix meets the requirements of AppSourceCop.json
```json
"mandatoryAffixes": [
    "ART CU ",
    "ART_CU_"
],
```

**Comment by deerware** [comment]
Edit: When I changed the settings
```diff
- "CRS.ObjectNamePrefix": "ART CU ",
+ "CRS.ObjectNamePrefix": "ART CU",
```

It does not loop around and just keeps the same, but I still think this issue should be addressed

**Comment by TKapitan** [comment]
It's related to this AL issue: https://github.com/microsoft/AL/issues/7057

**Comment by AbsolutelyFreeWeb** [comment]
It's also related to this, dashes are also giving errors: #272

**Comment by pri-kise** [comment]
@deerware have you tried out the new option to provide multiple affixes in the appsourcecop.json

**Comment by deerware** [comment]
@pri-kise I have just tried it. It seems to be working fine now.

Testing process:
- in settings.json "CRS.ObjectNamePrefix" was set to a value with spaces ("ART CU ")
- in AppSourceCop.json "mandatoryAffixes" includes the same value, and a variant without spaces ("ART CU ", "ARTCU_")
- ✅ when saved, report columns with "ARTCU_" prefix are not changed - 
- ✅ when saved, report columns without a matching prefix get the prefix from settings.json - 
  - ❌ when saved without a matching prefix, if the prefix in settings.json ends with a space, it still loops around

The looping around is a separate issue which can simply be fixed the user. The main issue is fixed.

Thank you for the fix.
