### ISSUE TITLE
Reorganize all Files not working with version 1.5.21 - switched back to version 1.5.19

### ISSUE THREAD

**Issue by PleachiM** [waldo1001/crs-al-language-extension#268]
Reorganize all Files not working with new Version 1.5.20 - 1.5.21

**Comment by waldo1001** [comment]
Any more info on the symptoms?

Is there an error message of any kind?

**Comment by PleachiM** [comment]
Hi, sorry! 
No there is no error. Just an output in VS Code
"5.12.2022, 14:33:23 - Reorganize all files" and nothing else. 
Also Reorganize Single File was not working.

**Comment by waldo1001** [comment]
I think I have a fix - please confirm in next release .. !

**Comment by waldo1001** [comment]
It's online .. v22 .. hopefully it works now 🤔

**Comment by PleachiM** [comment]
6.12.2022, 14:25:23 - Reorganize all files
6.12.2022, 14:25:23 - Rename file from T.al to Tab90102.MyTable.al
Works now. Thank you!
