### ISSUE TITLE
Filenames don't strip whitespaces in affixes

### ISSUE THREAD

**Issue by cegekaJG** [waldo1001/crs-al-language-extension#281]
When renaming a file, all whitespaces in the object name will be filtered out, with the exception of whitespaces in the affixes. This is an issue because with that whitespace, the file violates `AA0215`. However, without a whitespace in the affix, object names become hard to read.

For example:
Assuming a table object called `Vehicle` and a prefix called `BCE`, the new object name would become `BCEVehicle`, and the filename would be `BCEVehicle.Tab.al`.
But if the prefix were `BCE `, the new names would be `BCE Vehicle` and `BCE Vehicle.Tab.al`, respectively.

I'm a bit confused because in your [blog](https://www.waldo.be/2018/07/03/crs-al-language-extension-file-management/) you also have a whitespace in your prefix.
![img](http://www.waldo.be/wp-content/uploads/2018/07/070218_1626_CRSALLangua3.png)

**Comment by waldo1001** [comment]
Now I am confused - because on my end, it does strip the spaces..  🤔.

Can you share all your CRS settings?

**Comment by cegekaJG** [comment]
I figured it out - I originally included the `<Prefix>` tag in the name template because I had `RemovePrefixfromFilename` enabled. That one doesn't strip the whitespace.
Here are my new settings:
```json
"CRS.ExtensionObjectNamePattern": "<Prefix><BaseName>",
"CRS.FileNamePattern": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
"CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
"CRS.FileNamePatternPageCustomizations": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
"CRS.ObjectNamePrefix": "DUR ",
"CRS.ObjectNameSuffix": "",
"CRS.RenameWithGit": false
```
