### ISSUE TITLE
CRS rename file does not support extension objects with individual names

### ISSUE THREAD

**Issue by NKarolak** [waldo1001/crs-al-language-extension#305]
My settings are:
```
"CRS.ObjectNamePrefix": "AFFIX ",
"CRS.ExtensionObjectNamePattern": "<Prefix><BaseName>",
"CRS.FileNamePatternExtensions": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
"CRS.FileNamePattern": "<ObjectNameShort>.<ObjectTypeShortPascalCase>.al",
"CRS.RemovePrefixFromFilename": true
```

Previously, per app, we created only one extension object per base object, and the extension object was named after the base object:
`"CRS.ExtensionObjectNamePattern": "<Prefix><BaseName>",`

Since runtime 13.0, we can (and should) create multiple extension object per base object The base object can even be our own app object. This requires another extension object name pattern that is not implemented yet, something like:
`"CRS.ExtensionObjectNamePattern": "<Prefix><BaseName><Any>",`

As a result, (CRS) renaming the file for following object
`tableextension 50000 "AFFIX Customer 2" extends Customer`
will not rename the file at all (expected: Customer2.TableExt.al), but instead, it will rename the object:
`tableextension 50000 "AFFIX Customer" extends Customer`

Even if I completely remove CRS.ExtensionObjectNamePattern, then object name "AFFIX Customer 2"  will still be converted into  "AFFIX Customer" - why is that?

**Comment by waldo1001** [comment]
> Even if I completely remove CRS.ExtensionObjectNamePattern, then object name "AFFIX Customer 2" will still be converted into "AFFIX Customer" - why is that?

I'm going to assume you have the same setting on another level?

**Comment by NKarolak** [comment]
> I'm going to assume you have the same setting on another level?

Silly me. Yes, I hav the same settings also on user level, and I knew it, but for some weird reason I assumed yesterday that the levels are not considered setting by setting, but per extension (if one extension setting is defined on workspace level, don't consider any extension setting on user level).

**Comment by NKarolak** [comment]
> So .. what about I'd add this "any" myself, because I wouldn't want to depend on settings from people .. but just have it work with the settings you have already ... would that make sense?

Sorry, I don't get the question :D

**Comment by waldo1001** [comment]
basically meaning that I would add the "any" myself, meaning: in stead of going litterally `<Prefix><BaseName>`, I'd do something like `<Prefix><BaseName>.*`, and add the latter myself .. like .. anything that follows your pattern, is already ok .. if not, I'd change it into your pattern, and add nothing, resulting in possible double names.. but at least you'd be able to override it..?

**Comment by NKarolak** [comment]
Got it - I like that suggestion. But then you should explain this hidden implementation also here:
![image](https://github.com/waldo1001/crs-al-language-extension/assets/34504100/6f0a0967-8042-42d4-b47c-798d080868f5)

**Comment by waldo1001** [comment]
🫡

**Comment by waldo1001** [comment]
@NKarolak , should be part of this release.

**Comment by NKarolak** [comment]
It's working - thanks a lot for the prompt implementation :-)
