### ISSUE TITLE
Implement a better way to disable snippets

### ISSUE THREAD

**Issue by waldo1001** [waldo1001/crs-al-language-extension#32]
Now, it's going to rename the snippet-folder of the extension, but maybe it's better to:
- copy the files to a "disabled" folder
- empty the files

this way, there will be no extension-errors in the log anymore.

**Comment by megel** [comment]
Dont forgett to Re-Enable the snippets on uninstall.

**Comment by waldo1001** [comment]
@megel, fair enough :-)
for now, I changed the default setting to "false" so by default, it's not going to disable the default snippets anymore...

**Comment by KristofKlein** [comment]
Hi, I do get the following message/error and may ask if it has something to do how you handle snippets: 
> Disabled snippet-directory not found. - Source: CRS AL Language Extension (Extension)

Anyone a clue what that means? I can't say when it showed up the first time ( my guess is that due to GDPR the company enabled Bitlocker on all machines that something got broken) remove and reinstall of your extension did not help :(

**Comment by waldo1001** [comment]
@KristofKlein ,

it tries to disable snippets - and indeed, probably you're not allowed to.  You can remove te setting "CRS.DisableCRSSnippets" - or set it to false?

**Comment by waldo1001** [comment]
the problem is that there is actually no way to decently disable snippets... .  I'm now renaming the snippets-folder of the extension.  But that also results in quite some internal errors, which I don't like :(.
Another way would be to empty the files.  But I need to be able to re-enable them.  
So I'll probably end up in copying the folder to a new one, and create phantom-files at the original place.

Don't know it would solve your problem though...

**Comment by KristofKlein** [comment]
Well for me it complains that it can not find it. so maybe i just can create it manually and the message disapears :) so what is it called? About the User Settings - it looks like this right now:
```
  // Disable the default Al Snippets.  When you change the setting, you need to restart VSCode twice.  Once for disabling the snippets on activation (at that time, the snippets are still loaded).  And the second time to actually not load the snippets anymore
  "CRS.DisableCRSSnippets": false,

  // Disable the default Al Snippets.  When you change the setting, you need to restart VSCode twice.  Once for disabling the snippets on activation (at that time, the snippets are still loaded).  And the second time to actually not load the snippets anymore
  "CRS.DisableDefaultAlSnippets": false
```
(Just noticed the Description for both values is the same ;) )

**Comment by waldo1001** [comment]
oops.
for your error, it seems to be the "CRS.DisableCRSSnippets"

**Comment by KristofKlein** [comment]
took some time to follow up on thisone. I still have no success with this Snippets. I have DisableDefaultAlSnippets to True, and DisableCRS ( of course!! ) to false. Still I get the error. Still I can see both snippets. since it complains about the folder ... what folder is it talking about? what is the location it should be?
I guess around here %USERPROFILE%\.vscode\extensions\ ?! I just wanted to check what happens if i created it manually. If it drops the error I would be happy for now :)

**Comment by waldo1001** [comment]
@KristofKlein ,

indeed, it's searching in the %USERPROFILE%\.vscode\extensions\ for a folder that startswith "Microsoft.al".  WIthin that folder, it's will rename the "snippets" folder to "snippets-disabled".

Try to do that manually - you shouldn't be able to do that either - if so, it's a matter of security, I guess... 
or maybe for some reason, your folder is located in some other location?

**Comment by KristofKlein** [comment]
Hi @waldo1001 ! 
Went a bit further with this. So what I found in my extenstions folder looked like this:
Microsoft.al-0.15.18771 only had the folder bin inside. neither snippets nor snippets-disabled. but I do have a folder called: ms-dynamics-smb.al-0.15.18771. And this one has folders for snippets, syntaxes and alike :)

So maybe my installation is just messed up, or MS had some ideas on naming its extenfolder different. after sorting this out my issue has been disappeared :)

Thanks again for your great work!

**Comment by waldo1001** [comment]
Not sure - I think there is a "ms-dynamics-smb"-version, and a "microsoft" version.  In any case, my extension shouldn't error out - so I'm sure going to look into that.  At some point ;-)

**Comment by waldo1001** [comment]
This is a VSCode extension that does a perfect job:
https://marketplace.visualstudio.com/items?itemName=svipas.control-snippets
