### ISSUE TITLE
Intellisense on EventSubscriber Procedure

### ISSUE THREAD

**Issue by Schnieringer** [waldo1001/crs-al-language-extension#86]
Intellisense on EventSubscriber Procedure

For Example:

`  [EventSubscriber(ObjectType::Table, database::"Sales Line", 'OnAfterAssignItemValues', '', true, true)]`
New procedure: local procedure OnAfterAssignItemValues( STRG+SPACE now you get here first all the snippets from the crs.al-language extension... and in the end... SalesLine and Item... 

The crs-snippets should not open here.

![vs code crs extension deaktivated](https://user-images.githubusercontent.com/39938430/47350175-90b4e900-d6b5-11e8-9d2f-1c50084cfa16.png)
![vs code crs extension aktiviated](https://user-images.githubusercontent.com/39938430/47350176-90b4e900-d6b5-11e8-8201-924d41258ab2.png)

**Comment by waldo1001** [comment]
You are very right...

I noticed this as well - but no idea on how to fix this.  I have been trying to go through the package.json of the al-extension, but nothing helpful found ...

Do you happen to have an idea?

**Comment by Schnieringer** [comment]
Unfortunately, I don't have a solution here either. The question is how the AL Extension from Microsoft implemented their own snippets? The problem also affects other AL extensions :-) but that makes the list even longer until you finally get to the "right" parameters.

**Comment by waldo1001** [comment]
small tip, just press arrow up ;-)

In a way, they have just some snippets like I have, but they are able to avoid showing them on some places..  so i guess I'll need to figure out how they do that :-/

**Comment by Schnieringer** [comment]
small workaround... simply enter a point, then the snippets are not listed and only the correct parameters are displayed.
![workaround](https://user-images.githubusercontent.com/39938430/47547065-39e92280-d8f4-11e8-8445-e59be42f8cd1.jpg)

**Comment by waldo1001** [comment]
Thanks :-).

I will still search for a way to see how I can avoid showing the snippets on the places we don't want. If Microsoft isn't showing them, we should be able to hide them as well..
